import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
       <div className="w-screen h-screen bg-red-200 bg-gradient-to-b from-blue-100 to-red-100">
          <div className="h-24">
            <Navbar/>
          </div>
          <div className="h-[calc(100vh-96px)] container m-auto">
            {children}
          </div>
       </div>
        </body>
    </html>
  );
}
